version: "3"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${OMEKA_DB}
      MYSQL_USER: ${OMEKA_DB_USER}
      MYSQL_PASSWORD: ${OMEKA_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - db:/var/lib/mysql
    ports:
      - 33601:3601
  omeka-s:
    image: xentropics/omeka-s:${tag}
    links:
      - db:db
    restart: always
    depends_on:
      - db
    volumes:
      - omeka:/var/www/html/files
    environment:
      install_arkdeps: ${OMEKA_INSTALL_ARKDEPS}
      berkeleydb_lib: ${OMEKA_BERKELEYDB_LIB}
    ports:
      - 9001:80
volumes:
  db:
  omeka:
