version: "3"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${OMEKA_DB}
      MYSQL_USER: ${OMEKA_DB_USER}
      MYSQL_PASSWORD: ${OMEKA_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${OMEKA_DB_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
  omeka-s:
    image: xentropics/omeka-s:${OMEKA_IMAGE_TAG}
    links:
      - db:db
      - solr:solr
    restart: always
    depends_on:
      - db
    volumes:
      - omeka:/var/www/html/files
      - log:/var/log
      - type: bind
        source: ./profiles/${OMEKA_PROFILE}/profile.json
        target: /opt/imageboot/profile.json
        read_only: true
      - type: bind
        source: ./profiles/${OMEKA_PROFILE}/etc/apache-config.conf
        target: /etc/apache2/sites-enabled/000-default.conf
        read_only: true
      - type: bind
        source: ./profiles/${OMEKA_PROFILE}/etc/php.ini
        target: /usr/local/etc/php/php.ini
        read_only: true
      - type: bind
        source: ./profiles/${OMEKA_PROFILE}/etc/imagemagick-policy.xml
        target: /etc/ImageMagick/policy.xml
        read_only: true
      - type: bind
        source: ./profiles/${OMEKA_PROFILE}/etc/local.config.php
        target: /etc/local.config.php
        read_only: true
      - type: bind
        source: ./profiles/${OMEKA_PROFILE}/etc/.htaccess
        target: /var/www/html/.htaccess
        read_only: true
      - type: bind
        source: ./profiles/${OMEKA_PROFILE}/scripts
        target: /var/www/scripts
        read_only: true
        

    environment:
      install_arkdeps: ${OMEKA_INSTALL_ARKDEPS}
      berkeleydb_lib: ${OMEKA_BERKELEYDB_LIB}
      skip_modules: ${OMEKA_SKIP_MODULES}
    ports:
      - ${OMEKA_PORT}:80
  solr:
    image: solr:latest
    restart: always
    volumes:
      - solr:/var/solr
    command: solr-precreate omeka
    ports:
      - 8983:8983
volumes:
  db:
  omeka:
  log:
  solr:
