services:
  solr:
    image: solr:latest
    restart: always
    volumes:
      - solr:/var/solr
    command: solr-precreate omeka
    expose:
      - 8983
  omeka-s:
    links:
      - db:db
      - solr:solr
volumes:
  solr: