#!/bin/bash

echo "OMEKA_DB: $OMEKA_DB"
echo "OMEKA_DB_USER: $OMEKA_DB_USER"
echo "OMEKA_DB_PASSWORD: $OMEKA_DB_PASSWORD"
echo "OMEKA_INSTALL_ARKDEPS: $OMEKA_INSTALL_ARKDEPS"
echo "OMEKA_BERKELEYDB_LIB: $OMEKA_BERKELEYDB_LIB"
echo "OMEKA_SKIP_MODULES: $OMEKA_SKIP_MODULES"
echo "OMEKA_PROFILE: $OMEKA_PROFILE"
echo "OMEKA_IMAGE_TAG: $OMEKA_IMAGE_TAG"
